import { venueInterface } from "../interfaces";

export const venueList: venueInterface[] = [
  {
    name: "Blå",
    address: "Brenneriveien 9C",
    googleMapsURL: "https://goo.gl/maps/GAzmhe8fptAiXp8B6",
    website: "https://www.blaaoslo.no/",
    hidden: false,
  },
  {
    name: "Cosmopolite",
    address: "Vogts gate 64",
    googleMapsURL: "https://goo.gl/maps/rc6FTxEALzSFqf1H9",
    website: "https://cosmopolite.no/",
    hidden: false,
  },
  {
    name: "Dansens Hus",
    address: "Vulkan 1",
    googleMapsURL: "https://goo.gl/maps/JDEzSd4cgSjoKfJ96",
    website: "http://www.dansenshus.com/",
    hidden: false,
  },
  {
    name: "Den Norske Opera & Ballett",
    address: "Kirsten Flagstads Plass",
    googleMapsURL: "https://goo.gl/maps/3Mu6Yi7L4cZ9GprF6",
    website: "http://operaen.no/",
    hidden: true,
  },
  {
    name: "Vigelandsmuseet",
    address: "Nobels gate 32",
    googleMapsURL: "https://g.page/Vigelandmuseet?share",
    website: "http://www.vigeland.museum.no/",
    hidden: true,
  },
  {
    name: "Grønland kulturstasjon",
    address: "Tøyenbekken 5",
    googleMapsURL: "https://goo.gl/maps/jmRoq87BRCoMu3jk6",
    website: "http://oslo.kommune.no/kulturskolen",
    hidden: true,
  },
  {
    name: "Jæger",
    address: "Grensen 9",
    googleMapsURL: "https://goo.gl/maps/qNUAzDNKPe9BLN6w9",
    website: "http://jaegeroslo.no/",
    hidden: false,
  },
  {
    name: "Kulturkirken Jakob",
    address: "Hausmanns gate 14",
    googleMapsURL: "https://goo.gl/maps/xL2t3ZfU3eDxQzqH6",
    website: "http://www.jakob.no/",
    hidden: false,
  },
  {
    name: "Munch Museum",
    address: "Edvard Munchs Plass 1",
    googleMapsURL: "https://goo.gl/maps/xUvNtYQsA3SSR1j27",
    website: "http://munchmuseet.no/",
    hidden: true,
  },
  {
    name: "Internasjonalen",
    address: "Youngstorget 2A",
    googleMapsURL: "https://goo.gl/maps/sWmPMuHLzX5C5Rd37",
    website: "http://www.internasjonalen.no/",
    hidden: false,
  },
  {
    name: "Feber (Festivalkontor)",
    address: "Youngstorget 6",
    googleMapsURL: "https://g.page/feberoslo?share",
    website: "https://www.facebook.com/feberoslo/",
    hidden: true,
  },
  {
    name: "Nobels fredssenter",
    address: "Brynjulf Buls plass 1",
    googleMapsURL: "https://g.page/Nobelpeacecenter?share",
    website: "http://www.nobelpeacecenter.org/",
    hidden: true,
  },
  {
    name: "Sentralen",
    address: "Øvre Slottsgate 3",
    googleMapsURL: "https://g.page/sentralenkulturhus?share",
    website: "http://www.sentralen.no/",
    hidden: false,
  },
  {
    name: "Becco",
    address: "Kristian Augusts gate 11",
    googleMapsURL: "https://goo.gl/maps/oKeKf3g4GUFNqyzF7",
    website: "https://becco.no/",
    hidden: true,
  },
  {
    name: "Nordic Black Theatre",
    address: "Hollendergata 8",
    googleMapsURL: "https://goo.gl/maps/v3RjwEeyMoKkDr5r6",
    website: "http://www.nordicblacktheatre.no/",
    hidden: false,
  },
  {
    name: "Oslo Konserthus",
    address: "Munkedamsveien 14",
    googleMapsURL: "https://goo.gl/maps/eUKxedjbMuwQJbqL9",
    website: "http://www.oslokonserthus.no/",
    hidden: false,
  },
  {
    name: "Parkteatret",
    address: "Olaf Ryes plass 11",
    googleMapsURL: "https://goo.gl/maps/X7f99cw9uM5Gsb4U6",
    website: "http://www.parkteatret.no/",
    hidden: false,
  },
  {
    name: "Riksscenen",
    address: "Trondheimsveien 2",
    googleMapsURL: "https://g.page/Folkemusikkscenen?share",
    website: "http://www.riksscenen.no/",
    hidden: false,
  },
  {
    name: "Rockefeller Music Hall",
    address: "Badstugata 2",
    googleMapsURL: "https://goo.gl/maps/ADdYHoeKf7m7e1Fg7",
    website: "http://www.rockefeller.no/",
    hidden: false,
  },
  {
    name: "Sentrum Scene",
    address: "Arbeidersamfunnets plass 1",
    googleMapsURL: "https://goo.gl/maps/LcUzcEqx6aCu2MWw6",
    website: "http://www.rockefeller.no/",
    hidden: false,
  },
  {
    name: "Victoria Nasjonal Jazzscene",
    address: "Karl Johans gate 35",
    googleMapsURL: "https://goo.gl/maps/77M7apRccEud4KJy8",
    website: "http://www.nasjonaljazzscene.no/",
    hidden: false,
  },
  {
    name: "Kafé Hærverk",
    address: "Hausmanns gate 34",
    googleMapsURL: "https://goo.gl/maps/Jk3WwaUbBJefWpsD7",
    website: "https://kafe-haerverk.com/",
    hidden: false,
  },
  {
    name: "Trekanten",
    address: "St. Olavs Plass 5",
    googleMapsURL: "https://goo.gl/maps/zZow3qwE253oHzaRA",
    website: "http://www.trekantenoslo.no/",
    hidden: true,
  },
  {
    name: "Pressens Hus",
    address: "Skippergata 24",
    googleMapsURL: "https://goo.gl/maps/J5De2DPPRKNT7CDF9",
    website: "http://pressenshus.no/",
    hidden: true,
  },
  {
    name: "Melahuset",
    address: "Mariboes gate 8",
    googleMapsURL: "https://g.page/Melahuset?share",
    website: "http://mela.no/",
    hidden: false,
  },
  {
    name: "Asylet",
    address: "Grønland 28",
    googleMapsURL: "https://goo.gl/maps/Jps8Wecf6Q9yc6JM6",
    website: "http://www.asylet.no/",
    hidden: true,
  },
  {
    name: "Hammerhai",
    address: "Opergata 77",
    googleMapsURL: "https://goo.gl/maps/c9Jpo2bD4hUv7bfY6",
    website: "https://www.instagram.com/hammerhaibar/",
    hidden: true,
  },
  {
    name: "Baba Bar",
    address: "Hausmanns gate 8",
    googleMapsURL: "https://maps.app.goo.gl/VCFsZdmr2nXvDoX2A",
    website: "https://www.instagram.com/bababar_oslo/",
    hidden: false,
  },
  {
    name: "Dunk",
    address: "Bernt Ankers gate 21",
    googleMapsURL: "https://maps.app.goo.gl/NK16RrmEZAFkHhZb9",
    website: "http://www.dunkoslo.no/",
    hidden: false,
  },
  {
    name: "Fotogalleriet",
    address: "Møllergata 34",
    googleMapsURL: "https://maps.app.goo.gl/sAKnKB8sqZPT6tDm7",
    website: "https://www.fotogalleriet.no/",
    hidden: false,
  },
  {
    name: "Oslo Badstuforening - Sukkerbiten",
    address: "Sukkerbiten",
    googleMapsURL: "https://maps.app.goo.gl/n8Nxe5zBnS9cGdiu7",
    website: "http://www.oslobadstuforening.no/",
    hidden: false,
  },
  {
    name: "Tukthuset",
    address: "Youngsgate 5, Calmeyergate 1",
    googleMapsURL: "https://maps.app.goo.gl/NSX1uUho3KyHkpeG8",
    website: "http://www.tukthuset.no/",
    hidden: false,
  },
  {
    name: "Byens Tak",
    address: "Youngstorget 2A",
    googleMapsURL: "https://maps.app.goo.gl/1hqEWB1iVjqpzFdC7",
    website: "http://byenstak.com/",
    hidden: false,
  },
  {
    name: "Brugata 15",
    address: "Brugata 15, 0186 Oslo",
    googleMapsURL: "https://maps.app.goo.gl/yNAZrQM1HqyHWqqq7",
    website: "",
    hidden: false,
  },
  {
    name: "Cinemateket",
    address: "Dronningens gate 16",
    googleMapsURL: "https://maps.app.goo.gl/yhcAmjpMeeXr1wVa7",
    website: "http://www.cinemateket.no/",
    hidden: false,
  },
  {
    name: "Norges musikkhøgskole",
    address: "Slemdalsveien 11",
    googleMapsURL: "https://maps.app.goo.gl/dD5FMUv1FJgj5KZF8",
    website: "https://nmh.no/",
    hidden: false,
  },
  {
    name: "Deichman Bjørvika",
    address: "Anne-Cath, Vestlys plass 1",
    googleMapsURL: "https://maps.app.goo.gl/z4JuqYERvizNWTme8",
    website: "https://deichman.no/bibliotekene/bj%C3%B8rvika",
    hidden: false,
  },
  {
    name: "The National Museum",
    address: "Brynjulf Bulls plass 3",
    googleMapsURL: "https://maps.app.goo.gl/4NdEibrijkSsQhbq6",
    website: "https://www.nasjonalmuseet.no/en/",
    hidden: false,
  },
];
// ] as const satisfies readonly venueInterface[];
