import { venueInterface } from "../interfaces";

export const venueList: venueInterface[] = [
  {
    name: "Blå",
    address: "Brenneriveien 9C",
    googleMapsURL: "https://goo.gl/maps/GAzmhe8fptAiXp8B6",
    website: "https://www.blaaoslo.no/",
  },
  {
    name: "Cosmopolite",
    address: "Vogts gate 64",
    googleMapsURL: "https://goo.gl/maps/rc6FTxEALzSFqf1H9",
    website: "https://cosmopolite.no/",
  },
  {
    name: "Dansens Hus",
    address: "Vulkan 1",
    googleMapsURL: "https://goo.gl/maps/JDEzSd4cgSjoKfJ96",
    website: "http://www.dansenshus.com/",
  },
  {
    name: "Den Norske Opera & Ballett",
    address: "Kirsten Flagstads Plass",
    googleMapsURL: "https://goo.gl/maps/3Mu6Yi7L4cZ9GprF6",
    website: "http://operaen.no/",
  },
  {
    name: "Vigelandsmuseet",
    address: "Nobels gate 32",
    googleMapsURL: "https://g.page/Vigelandmuseet?share",
    website: "http://www.vigeland.museum.no/",
  },
  {
    name: "Grønland kulturstasjon",
    address: "Tøyenbekken 5",
    googleMapsURL: "https://goo.gl/maps/jmRoq87BRCoMu3jk6",
    website: "http://oslo.kommune.no/kulturskolen",
  },
  {
    name: "Jaeger",
    address: "Grensen 9",
    googleMapsURL: "https://goo.gl/maps/qNUAzDNKPe9BLN6w9",
    website: "http://jaegeroslo.no/",
  },
  {
    name: "Kulturkirken Jakob",
    address: "Hausmanns gate 14",
    googleMapsURL: "https://goo.gl/maps/xL2t3ZfU3eDxQzqH6",
    website: "http://www.jakob.no/",
  },
  {
    name: "Munch Museum",
    address: "Edvard Munchs Plass 1",
    googleMapsURL: "https://goo.gl/maps/xUvNtYQsA3SSR1j27",
    website: "http://munchmuseet.no/",
  },
  {
    name: "Internasjonalen",
    address: "Youngstorget 2",
    googleMapsURL: "https://goo.gl/maps/sWmPMuHLzX5C5Rd37",
    website: "http://www.internasjonalen.no/",
  },
  {
    name: "Feber (Festivalkontor)",
    address: "Youngstorget 6",
    googleMapsURL: "https://g.page/feberoslo?share",
    website: "https://www.facebook.com/feberoslo/",
  },
  {
    name: "Nobels fredssenter",
    address: "Brynjulf Buls plass 1",
    googleMapsURL: "https://g.page/Nobelpeacecenter?share",
    website: "http://www.nobelpeacecenter.org/",
  },
  {
    name: "Sentralen",
    address: "Øvre Slottsgate 3",
    googleMapsURL: "https://g.page/sentralenkulturhus?share",
    website: "http://www.sentralen.no/",
  },
  {
    name: "Becco",
    address: "Kristian Augusts gate 11",
    googleMapsURL: "https://goo.gl/maps/oKeKf3g4GUFNqyzF7",
    website: "https://becco.no/",
  },
  {
    name: "Nordic Black Theatre & Cafeteatret",
    address: "Hollendergata 8",
    googleMapsURL: "https://goo.gl/maps/v3RjwEeyMoKkDr5r6",
    website: "http://www.nordicblacktheatre.no/",
  },
  {
    name: "Oslo Konserthus",
    address: "Munkedamsveien 14",
    googleMapsURL: "https://goo.gl/maps/eUKxedjbMuwQJbqL9",
    website: "http://www.oslokonserthus.no/",
  },
  {
    name: "Parkteatret",
    address: "Olaf Ryes plass 11",
    googleMapsURL: "https://goo.gl/maps/X7f99cw9uM5Gsb4U6",
    website: "http://www.parkteatret.no/",
  },
  {
    name: "Riksscenen",
    address: "Trondheimsveien 2",
    googleMapsURL: "https://g.page/Folkemusikkscenen?share",
    website: "http://www.riksscenen.no/",
  },
  {
    name: "Rockefeller Music Hall",
    address: "Badstugata 2",
    googleMapsURL: "https://goo.gl/maps/ADdYHoeKf7m7e1Fg7",
    website: "http://www.rockefeller.no/",
  },
  {
    name: "Sentrum Scene",
    address: "Arbeidersamfunnets plass 1",
    googleMapsURL: "https://goo.gl/maps/LcUzcEqx6aCu2MWw6",
    website: "http://www.rockefeller.no/",
  },
  {
    name: "Victoria Nasjonal Jazzscene",
    address: "Karl Johans gate 35",
    googleMapsURL: "https://goo.gl/maps/77M7apRccEud4KJy8",
    website: "http://www.nasjonaljazzscene.no/",
  },
  {
    name: "Hærverk",
    address: "Hausmanns gate 34",
    googleMapsURL: "https://goo.gl/maps/Jk3WwaUbBJefWpsD7",
    website: "https://kafe-haerverk.com/",
  },
  {
    name: "Trekanten",
    address: "St. Olavs Plass 5",
    googleMapsURL: "https://goo.gl/maps/zZow3qwE253oHzaRA",
    website: "http://www.trekantenoslo.no/",
  },
  {
    name: "Pressens Hus",
    address: "Skippergata 24",
    googleMapsURL: "https://goo.gl/maps/J5De2DPPRKNT7CDF9",
    website: "http://pressenshus.no/",
  },
  {
    name: "Melahuset",
    address: "Mariboes gate 8",
    googleMapsURL: "https://g.page/Melahuset?share",
    website: "http://mela.no/",
  },
  {
    name: "Asylet",
    address: "Grønland 28",
    googleMapsURL: "https://goo.gl/maps/Jps8Wecf6Q9yc6JM6",
    website: "http://www.asylet.no/",
  },
  {
    name: "Hammerhai",
    address: "Opergata 77",
    googleMapsURL: "https://goo.gl/maps/c9Jpo2bD4hUv7bfY6",
    website: "https://www.instagram.com/hammerhaibar/",
  },
];
